реализована функциональность "Общие фильмы"
IgorMapkIvanov/java-filmorate pull request #6
Opened 2022-08-17 20:39 UTC by IrinaSiliveeva

Добавлена функциональность "Общие фильмы". Оставлен комментарий в коде касаемо внесенных изменений в изначальную версию.

2022-08-18 18:10 UTC, IgorMapkIvanov requested changes
Тесты это не проверяют, но отправлять лучше полностью заполненный объект класса

2022-08-18 18:10 UTC, IgorMapkIvanov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbRepository.java
> +        String sql = "select f.* from  FILMS f, LIKES l1, LIKES l2 " +
Здесь у тебя возвращается список фильмов у которых МРА будет { id = mpa, name = null}, если добавить в sql join MPA таблицы и поле name в выборку, то MPA в фильме будет полноценный.

2022-08-18 18:10 UTC, IgorMapkIvanov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbRepository.java
> +        String sql = "select f.* from  FILMS f, LIKES l1, LIKES l2 " +
String sql = "select f.*, m.name from  FILMS f, MPA m, LIKES l1, LIKES l2 " + и все будет ок

2022-08-19 13:04 UTC, IgorMapkIvanov approved these changes

2022-08-19 13:04 UTC, IgorMapkIvanov commented on src/main/java/ru/yandex/practicum/filmorate/dao/LikesRepository.java
> -    public void deleteUserLikes(Long id) {
Вот это должно пропасть после обновления из develop в свою ветку

2022-08-19 13:04 UTC, IgorMapkIvanov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbRepository.java
> -    private final FilmGenresRepository filmGenresRepository;
Это тоже пропадет

2022-08-19 13:04 UTC, IgorMapkIvanov commented on src/main/resources/schema.sql
> +        foreign key (DIRECTOR_ID) references DIRECTORS
Это добавиться само

2022-08-19 13:11 UTC, RikDowson approved these changes

2022-08-19 14:05 UTC, IgorMapkIvanov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbRepository.java
> +        String sql = "select f.*, m.ID,MPA_ID, m.NAME MPA_NAME " +
String sql = "select f.*, **m.ID,MPA_ID,** m.NAME MPA_NAME " +
f.* там уже есть MPA_ID так что выделенное можно убрать

2022-08-19 14:12 UTC, IgorMapkIvanov requested changes

2022-08-19 14:12 UTC, IgorMapkIvanov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbRepository.java
> +        String sql = "select f.*, m.ID,MPA_ID, m.NAME MPA_NAME " +
в ответе который придет от БД будет 3 столбца с МРА ID
первый из f.*
второй m.ID
третий опять из таблицы фильмов MPA_ID из-за запятой между m.ID и MPA_ID
достаточно будет SELECT f.*, m.NAME MPA_NAME

2022-08-20 15:26 UTC, IgorMapkIvanov approved these changes

2022-08-20 15:26 UTC, merged