Add director
IgorMapkIvanov/java-filmorate pull request #7
Opened 2022-08-18 16:55 UTC by RomanZbruev

2022-08-18 18:03 UTC, IgorMapkIvanov commented
Лайк за умение писать в стиле автора))))) как свой код читал!

2022-08-18 18:07 UTC, IgorMapkIvanov approved these changes
Все ок, есть пожелание, но оно на усмотрения автора

2022-08-18 18:07 UTC, IgorMapkIvanov commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDbRepository.java
> +        else if(sort.equals("likes")){
Возможно лишнее , но я бы у sorted.upLowCase сделал, мало какой year и likes прилетит

2022-08-19 12:08 UTC, IrinaSiliveeva approved these changes

2022-08-19 12:29 UTC, IgorMapkIvanov requested changes
Нужно подтянуть изменения с последнего PR

2022-08-19 15:25 UTC, IgorMapkIvanov approved these changes

2022-08-19 15:25 UTC, merged